### PR TITLE
Replace IsOriginalValue() with IsModified and fix merging and casting of default option values

### LINKED ISSUE #2198: IsOriginalValue() always returns False after merging
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

After merging two configurations (or using `$PesterPreference`), `IsOriginalValue()` will return False even if both configurations had original values for an option.

### Expected Behavior

Should return True or False depending on whether its actually modified

### Steps To Reproduce

```powershell
$one = New-PesterConfiguration
$two = New-PesterConfiguration
$merge = [PesterConfiguration]::Merge($one,$two)
$merge.Output.CIFormat.IsOriginalValue()
False
```

### Describe your environment

_No response_

### Possible Solution?

_No response_

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
Only modify configuration options that have actually been changed when casting and merging configurations.

`Option.IsOriginalValue()` is marked obsolete and is replaced by a new `Option.IsModified`-property that enables us to fix merging of serialized PesterConfiguration.

Fix #2198

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [x] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by fflaten** [comment]
@nohwnd:
- Thoughts on this?
- Any reason not to replace `IsOriginalValue()` with `IsOriginalValue`-property with only a getter? That would expose the state when serializing and deserializing `PesterConfiguration`-objects which should let us keep the status after deserialization. The new formats will still keep it hidden in default view.
  - Or keep both if we believe someone's using the method outside runtime-code

File: src/csharp/Pester/CodeCoverageConfiguration.cs [hunk 1]
```diff
@@ -57,17 +57,16 @@ public CodeCoverageConfiguration(IDictionary configuration) : this()
...
-                OutputPath = configuration.GetObjectOrNull<string>("OutputPath") ?? OutputPath;
-                OutputEncoding = configuration.GetObjectOrNull<string>("OutputEncoding") ?? OutputEncoding;
-                Path = configuration.GetArrayOrNull<string>("Path") ?? Path;
-                ExcludeTests = configuration.GetValueOrNull<bool>("ExcludeTests") ?? ExcludeTests;
-                RecursePaths = configuration.GetValueOrNull<bool>("RecursePaths") ?? RecursePaths;
-                CoveragePercentTarget = configuration.GetValueOrNull<decimal>("CoveragePercentTarget") ?? CoveragePercentTarget;
-
-                SingleHitBreakpoints = configuration.GetValueOrNull<bool>("SingleHitBreakpoints") ?? SingleHitBreakpoints;
-                UseBreakpoints = configuration.GetValueOrNull<bool>("UseBreakpoints") ?? UseBreakpoints;
+                if (configuration.GetValueOrNull<bool>(nameof(Enabled)) is bool enabled) { Enabled = enabled; };
```
Comment (nohwnd) [inline src/csharp/Pester/CodeCoverageConfiguration.cs:60]: This looks like a lot of repeated code that can be done wrong in one or two places. I would rather see this in a method, and using `is not null` or `!= null` rather than `is <type>`.

IMHO you are checking to see if the value is not null, because GetValueOrNull already guarantees the given T type is returned.

Nice to see return to nameof, I had that everywhere but for some reason that I don't remember it did not work, and I reverted to just names. Maybe I was trying to avoid shipping dll, and compile in-line.

```cs
configuration.AssignValueIfNotNull<bool>(nameof(Enabled), v => Enabled = v);

public static void AssignValueIfNotNull<T>(this IDictionary dictionary, string key, Action<T> assign) 
where T : struct
{
    var value = GetValueOrNull<T>(dictionary, key);
    if (value != null)
    {
        assign(value.Value);
    }
}

```

Comment (fflaten) [reply src/csharp/Pester/CodeCoverageConfiguration.cs:60]: > IMHO you are checking to see if the value is not null, because GetValueOrNull already guarantees the given T type is returned.

Fair point. Shortsighted in the heat of the moment. Had to get something to work for the Ansi-option which I'll now probably skip. Will still fix this though for future use.

Love the generic extension-method. 💯 will steal 😄

**Comment by fflaten** [comment]
Ready for review.
I could change to `IsDefaultValue` if you'd like to avoid mini-breaking change and keep `IsOriginalValue()`.

**Comment by nohwnd** [comment]
IsDefaultValue seems like better name. Please put IsOriginalValue() back and mark it deprecated (with Obsolete attribute). Just to be nice about semantic versioning.

**Comment by fflaten** [comment]
> IsDefaultValue seems like better name.

After letting the name sink in, it could confuse someone when it's false while Default and Value are equal (but modified). 😅. Naming is hard. `IsModified`?

**Review by nohwnd — APPROVED** [review]
